### ISSUE TITLE
[feature request] Add build instructions

### ISSUE THREAD

**Issue by osbm** [DesyncTheThird/corne-keymap#1]
hello, this is an awesome repository and i love the clean way you manage your keymap. i am trying to customize and play around with my config too. Can you explain your build process in readme ?

**Comment by DesyncTheThird** [comment]
Clone the repo into `qmk_firmware\keyboards\crkbd\keymaps\<keymap name>`, and install the achordion feature as per [these instructions](https://getreuer.info/posts/keyboards/achordion/index.html#add-achordion-to-your-keymap) (just step 4), then build it in the CLI with `qmk compile -c -kb crkbd -km <keymap name>`, optionally with an extra `-e CONVERT_TO=` flag. 

(I use non-sparkfun RP2040 MCUs, so my full command would be `qmk compile -c -kb crkbd -km desync -e CONVERT_TO=rp2040_ce`.) You can find the full list of converters [here](https://docs.qmk.fm/feature_converters#supported-converters). As an aside, I don't think this keymap will fit on a normal AVR pro micro, as there are quite a lot of features -- my uf2 file is 212kb when compiled.

If you're having any trouble with compiling, drop another comment here or maybe ask on the [QMK discord](https://discord.com/invite/qmk), as there's usually someone around there.

**Comment by osbm** [comment]
thank you for adding the instructions. I also want to switch to the rp2040 pro-micro. And be able to add the oled screen.
![Untitled](https://github.com/user-attachments/assets/acb32b98-7dea-490a-8fe4-7b4cba3c5637)
I am currently in tinkering stage. Hopefully i can make this work someday. Thanks alot. :heart:
